# -*- coding: utf-8 -*-
"""fixed_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L5Y0Vane-wqOoxoLkhdBRm7UaAhL3N5K
"""

# Install TensorFlow Datasets
!pip install tensorflow-datasets

import numpy as np
import tensorflow_datasets as tfds

# Load EMNIST letters dataset
(train_ds, test_ds), ds_info = tfds.load(
    'emnist/letters',
    split=['train', 'test'],
    as_supervised=True,
    with_info=True
)

# Convert train dataset
for images, labels in train_ds.batch(124800).take(1):
    X_train_letter = images.numpy()
    y_train_letter = labels.numpy()

# Convert test dataset
for images, labels in test_ds.batch(20800).take(1):
    X_test_letter = images.numpy()
    y_test_letter = labels.numpy()

print("Training:", X_train_letter.shape)
print("Testing:", X_test_letter.shape)

X_train_letter

y_train_letter

print(X_train_letter.shape)
print(y_train_letter.shape)

print(X_test_letter.shape)
print(y_test_letter.shape)

import matplotlib.pyplot as plt
import numpy as np

# Find image whose label is C (3)
index = np.where(y_train_letter == 3)[0][0]

plt.imshow(X_train_letter[index].squeeze(), cmap='gray')
plt.show()

print("Alphabet = C")

import matplotlib.pyplot as plt
import numpy as np

img = np.rot90(X_train_letter[index].squeeze(), -1)
img = np.fliplr(img)

plt.imshow(img, cmap='gray')
plt.show()

print("Alphabet = C")

import matplotlib.pyplot as plt
import numpy as np

# Find image whose label is D (4)
index = np.where(y_train_letter == 4)[0][0]

plt.imshow(X_train_letter[index].squeeze(), cmap='gray')
plt.show()

print("Alphabet = D")

import matplotlib.pyplot as plt
import numpy as np

# Find image whose label is E (5)
index = np.where(y_train_letter == 5)[0][0]

plt.imshow(X_train_letter[index].squeeze(), cmap='gray')
plt.show()

print("Alphabet = E")

import matplotlib.pyplot as plt
import numpy as np

img = np.rot90(X_train_letter[index].squeeze(), -1)
img = np.fliplr(img)

plt.imshow(img, cmap='gray')
plt.show()

print("Alphabet = E")

import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(15,10))

for letter in range(1,27):   # A=1 to Z=26

    # Find first occurrence of each alphabet
    index = np.where(y_train_letter == letter)[0][0]

    plt.subplot(5,6,letter)
    plt.imshow(X_train_letter[index].squeeze(), cmap='gray')
    plt.title(chr(letter + 64))
    plt.axis('off')

plt.tight_layout()
plt.show()

print(X_train_letter.shape)
print(y_train_letter.shape)

print(X_test_letter.shape)
print(y_test_letter.shape)

X_train_letter = X_train_letter.reshape(88800, 784)
X_test_letter = X_test_letter.reshape(14800, 784)

X_train_letter.shape

import matplotlib.pyplot as plt

# Data
dimensions = ['Images', 'Pixels']
values = [88800, 784]

# Graph
plt.bar(dimensions, values)

plt.title("EMNIST Alphabet Dataset Shape")
plt.xlabel("Components")
plt.ylabel("Count")

plt.show()

import matplotlib.pyplot as plt

plt.imshow(X_train_letter[0].reshape(28,28), cmap='gray')

alphabet = chr(y_train_letter[0] + 64)

plt.title("Alphabet : " + alphabet)

plt.show()

X_train_letter

X_test_letter

print(np.unique(X_train_letter[0]))

"""... hides many values in the middle

"""

y_train_letter

y_test_letter

y_train_letter.shape

from tensorflow.keras.utils import to_categorical

y_train_letter = to_categorical(y_train_letter, num_classes=27)
y_test_letter = to_categorical(y_test_letter, num_classes=27)

y_train_letter[1]

y_test_letter[1]

import tensorflow as tf

# Creating base neural network
model = tf.keras.Sequential([

    # First Hidden Layer
    tf.keras.layers.Dense(256, activation='relu', input_shape=(784,)),

    # Second Hidden Layer
    tf.keras.layers.Dense(64, activation='relu'),

    # Third Hidden Layer
    tf.keras.layers.Dense(64, activation='relu'),

    # Output Layer for A–Z
    tf.keras.layers.Dense(27, activation='softmax')

])

model.summary()

# Output layer
model.layers[-1]

# Compiling the model
model.compile(
    loss='categorical_crossentropy',   # Loss Function
    optimizer='adam',                  # Optimizer
    metrics=['accuracy']               # Evaluation Metric
)

# Training the model

history = model.fit(
    X_train_letter,
    y_train_letter,
    batch_size=100,
    epochs=10,
    validation_data=(X_test_letter, y_test_letter)
)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Convert one-hot encoded labels back to normal labels
y_test_letter_eval = np.argmax(y_test_letter, axis=1)

# Predict test images
y_predicts = model.predict(X_test_letter)
y_predicts = np.argmax(y_predicts, axis=1)

# Confusion Matrix
con_mat = confusion_matrix(y_test_letter_eval, y_predicts)

# Alphabet labels
labels = [chr(i+64) for i in range(1,27)]

plt.figure(figsize=(15,15))

sns.heatmap(
    con_mat[1:,1:],     # ignore class 0
    annot=True,
    fmt='d',
    cmap='gray',
    xticklabels=labels,
    yticklabels=labels
)

plt.title(
    "Confusion Matrix for Alphabet Recognition",
    fontweight='bold',
    fontsize=15
)

plt.xlabel("Predicted Alphabet")
plt.ylabel("Actual Alphabet")

plt.show()

from sklearn.metrics import classification_report
import numpy as np

# Convert one-hot encoded labels back to normal labels
y_test_letter_eval = np.argmax(y_test_letter, axis=1)

# Predict test images
y_predicts = model.predict(X_test_letter)
y_predicts = np.argmax(y_predicts, axis=1)

# Alphabet labels A–Z
alphabet_labels = [chr(i+64) for i in range(1,27)]

# Generate report
print(
    classification_report(
        y_test_letter_eval,
        y_predicts,
        labels=range(1,27),
        target_names=alphabet_labels
    )
)

print(history.history.keys())

# summarize history for accuracy
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='best')
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='best')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Find alphabet A (A = 1)
i = np.where(np.argmax(y_test_letter, axis=1) == 1)[0][0]

# Predict single image
y_predict_single = model.predict(X_test_letter[[i]])
y_predict_single = np.argmax(y_predict_single, axis=1)

# Convert labels to alphabets
actual = chr(np.argmax(y_test_letter[i]) + 64)
predicted = chr(y_predict_single[0] + 64)

# Display image
plt.imshow(X_test_letter[i].reshape(28,28), cmap='gray')

plt.xlabel(
    "Actual:{} Pred:{}".format(
        actual,
        predicted
    )
)

plt.show()

# Rotate and flip the image before displaying:

import numpy as np
import matplotlib.pyplot as plt

img = X_test_letter[i].reshape(28,28)

# Correct orientation
img = np.rot90(img, -1)
img = np.fliplr(img)

# Display image
plt.imshow(X_test_letter[i].reshape(28,28), cmap='gray')

plt.xlabel(
    "Actual:{} Pred:{}".format(
        actual,
        predicted
    )
)

plt.imshow(img, cmap='gray')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Find alphabet B (B = 2)
i = np.where(np.argmax(y_test_letter, axis=1) == 2)[0][0]

# Predict single image
y_predict_single = model.predict(X_test_letter[[i]])
y_predict_single = np.argmax(y_predict_single, axis=1)

# Convert labels to alphabets
actual = chr(np.argmax(y_test_letter[i]) + 64)
predicted = chr(y_predict_single[0] + 64)

# Display image
plt.imshow(X_test_letter[i].reshape(28,28), cmap='gray')

plt.xlabel(
    "Actual:{} Pred:{}".format(
        actual,
        predicted
    )
)

plt.show()

# Rotate and flip the image before displaying:

import numpy as np
import matplotlib.pyplot as plt

img = X_test_letter[i].reshape(28,28)

# Correct orientation
img = np.rot90(img, -1)
img = np.fliplr(img)

# Display image
plt.imshow(X_test_letter[i].reshape(28,28), cmap='gray')

plt.xlabel(
    "Actual:{} Pred:{}".format(
        actual,
        predicted
    )
)

plt.imshow(img, cmap='gray')
plt.show()